// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alternative struct {
	ID              pgtype.UUID `json:"id"`
	SourceLibraryID pgtype.UUID `json:"source_library_id"`
	TargetLibraryID pgtype.UUID `json:"target_library_id"`
	Relationship    string      `json:"relationship"`
	Reason          string      `json:"reason"`
}

type Category struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

type CollectionRun struct {
	ID                 pgtype.UUID        `json:"id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	Status             string             `json:"status"`
	LibrariesProcessed int32              `json:"libraries_processed"`
	LibrariesSucceeded int32              `json:"libraries_succeeded"`
	LibrariesFailed    int32              `json:"libraries_failed"`
	SuccessRate        pgtype.Numeric     `json:"success_rate"`
	Errors             []byte             `json:"errors"`
	Trigger            string             `json:"trigger"`
}

type CollectionRunItem struct {
	ID            pgtype.UUID        `json:"id"`
	RunID         pgtype.UUID        `json:"run_id"`
	LibraryID     pgtype.UUID        `json:"library_id"`
	CollectorType string             `json:"collector_type"`
	Status        string             `json:"status"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	DurationMs    int32              `json:"duration_ms"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type Library struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Registry          string             `json:"registry"`
	PackageName       string             `json:"package_name"`
	GithubRepo        string             `json:"github_repo"`
	Description       string             `json:"description"`
	HomepageUrl       pgtype.Text        `json:"homepage_url"`
	License           string             `json:"license"`
	LatestVersion     string             `json:"latest_version"`
	LatestVersionDate pgtype.Timestamptz `json:"latest_version_date"`
	Deprecated        bool               `json:"deprecated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Metadata          []byte             `json:"metadata"`
}

type LibraryCategory struct {
	LibraryID  pgtype.UUID `json:"library_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type Score struct {
	ID                pgtype.UUID        `json:"id"`
	LibraryID         pgtype.UUID        `json:"library_id"`
	ScoredAt          pgtype.Timestamptz `json:"scored_at"`
	OverallScore      pgtype.Numeric     `json:"overall_score"`
	MaintenanceHealth pgtype.Numeric     `json:"maintenance_health"`
	ApiClarity        pgtype.Numeric     `json:"api_clarity"`
	DocQuality        pgtype.Numeric     `json:"doc_quality"`
	SecurityPosture   pgtype.Numeric     `json:"security_posture"`
	CommunitySignal   pgtype.Numeric     `json:"community_signal"`
	DeprecationSafety pgtype.Numeric     `json:"deprecation_safety"`
	ScoringVersion    string             `json:"scoring_version"`
	RawData           []byte             `json:"raw_data"`
}
