// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (slug, name, description, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, description, parent_id
`

type CreateCategoryParams struct {
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const createCollectionRun = `-- name: CreateCollectionRun :one
INSERT INTO collection_runs (trigger) VALUES ($1) RETURNING id, started_at, completed_at, status, libraries_processed, libraries_succeeded, libraries_failed, success_rate, errors, trigger
`

func (q *Queries) CreateCollectionRun(ctx context.Context, trigger string) (CollectionRun, error) {
	row := q.db.QueryRow(ctx, createCollectionRun, trigger)
	var i CollectionRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.LibrariesProcessed,
		&i.LibrariesSucceeded,
		&i.LibrariesFailed,
		&i.SuccessRate,
		&i.Errors,
		&i.Trigger,
	)
	return i, err
}

const createCollectionRunItem = `-- name: CreateCollectionRunItem :one
INSERT INTO collection_run_items (run_id, library_id, collector_type)
VALUES ($1, $2, $3)
RETURNING id, run_id, library_id, collector_type, status, error_message, duration_ms, completed_at
`

type CreateCollectionRunItemParams struct {
	RunID         pgtype.UUID `json:"run_id"`
	LibraryID     pgtype.UUID `json:"library_id"`
	CollectorType string      `json:"collector_type"`
}

func (q *Queries) CreateCollectionRunItem(ctx context.Context, arg CreateCollectionRunItemParams) (CollectionRunItem, error) {
	row := q.db.QueryRow(ctx, createCollectionRunItem, arg.RunID, arg.LibraryID, arg.CollectorType)
	var i CollectionRunItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LibraryID,
		&i.CollectorType,
		&i.Status,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CompletedAt,
	)
	return i, err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (name, registry, package_name, github_repo, description, homepage_url, license)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, registry, package_name, github_repo, description, homepage_url, license, latest_version, latest_version_date, deprecated, created_at, updated_at, metadata
`

type CreateLibraryParams struct {
	Name        string      `json:"name"`
	Registry    string      `json:"registry"`
	PackageName string      `json:"package_name"`
	GithubRepo  string      `json:"github_repo"`
	Description string      `json:"description"`
	HomepageUrl pgtype.Text `json:"homepage_url"`
	License     string      `json:"license"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createLibrary,
		arg.Name,
		arg.Registry,
		arg.PackageName,
		arg.GithubRepo,
		arg.Description,
		arg.HomepageUrl,
		arg.License,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Registry,
		&i.PackageName,
		&i.GithubRepo,
		&i.Description,
		&i.HomepageUrl,
		&i.License,
		&i.LatestVersion,
		&i.LatestVersionDate,
		&i.Deprecated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const createScore = `-- name: CreateScore :one
INSERT INTO scores (
    library_id, overall_score,
    maintenance_health, api_clarity, doc_quality,
    security_posture, community_signal, deprecation_safety,
    scoring_version, raw_data
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, library_id, scored_at, overall_score, maintenance_health, api_clarity, doc_quality, security_posture, community_signal, deprecation_safety, scoring_version, raw_data
`

type CreateScoreParams struct {
	LibraryID         pgtype.UUID    `json:"library_id"`
	OverallScore      pgtype.Numeric `json:"overall_score"`
	MaintenanceHealth pgtype.Numeric `json:"maintenance_health"`
	ApiClarity        pgtype.Numeric `json:"api_clarity"`
	DocQuality        pgtype.Numeric `json:"doc_quality"`
	SecurityPosture   pgtype.Numeric `json:"security_posture"`
	CommunitySignal   pgtype.Numeric `json:"community_signal"`
	DeprecationSafety pgtype.Numeric `json:"deprecation_safety"`
	ScoringVersion    string         `json:"scoring_version"`
	RawData           []byte         `json:"raw_data"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.LibraryID,
		arg.OverallScore,
		arg.MaintenanceHealth,
		arg.ApiClarity,
		arg.DocQuality,
		arg.SecurityPosture,
		arg.CommunitySignal,
		arg.DeprecationSafety,
		arg.ScoringVersion,
		arg.RawData,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ScoredAt,
		&i.OverallScore,
		&i.MaintenanceHealth,
		&i.ApiClarity,
		&i.DocQuality,
		&i.SecurityPosture,
		&i.CommunitySignal,
		&i.DeprecationSafety,
		&i.ScoringVersion,
		&i.RawData,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, slug, name, description, parent_id FROM categories WHERE slug = $1
`

func (q *Queries) GetCategory(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, name, description, parent_id FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const getLatestScore = `-- name: GetLatestScore :one
SELECT id, library_id, scored_at, overall_score, maintenance_health, api_clarity, doc_quality, security_posture, community_signal, deprecation_safety, scoring_version, raw_data FROM scores
WHERE library_id = $1
ORDER BY scored_at DESC
LIMIT 1
`

func (q *Queries) GetLatestScore(ctx context.Context, libraryID pgtype.UUID) (Score, error) {
	row := q.db.QueryRow(ctx, getLatestScore, libraryID)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ScoredAt,
		&i.OverallScore,
		&i.MaintenanceHealth,
		&i.ApiClarity,
		&i.DocQuality,
		&i.SecurityPosture,
		&i.CommunitySignal,
		&i.DeprecationSafety,
		&i.ScoringVersion,
		&i.RawData,
	)
	return i, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, registry, package_name, github_repo, description, homepage_url, license, latest_version, latest_version_date, deprecated, created_at, updated_at, metadata FROM libraries WHERE id = $1
`

func (q *Queries) GetLibrary(ctx context.Context, id pgtype.UUID) (Library, error) {
	row := q.db.QueryRow(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Registry,
		&i.PackageName,
		&i.GithubRepo,
		&i.Description,
		&i.HomepageUrl,
		&i.License,
		&i.LatestVersion,
		&i.LatestVersionDate,
		&i.Deprecated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getLibraryBySlug = `-- name: GetLibraryBySlug :one
SELECT id, name, registry, package_name, github_repo, description, homepage_url, license, latest_version, latest_version_date, deprecated, created_at, updated_at, metadata FROM libraries WHERE registry = $1 AND package_name = $2
`

type GetLibraryBySlugParams struct {
	Registry    string `json:"registry"`
	PackageName string `json:"package_name"`
}

func (q *Queries) GetLibraryBySlug(ctx context.Context, arg GetLibraryBySlugParams) (Library, error) {
	row := q.db.QueryRow(ctx, getLibraryBySlug, arg.Registry, arg.PackageName)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Registry,
		&i.PackageName,
		&i.GithubRepo,
		&i.Description,
		&i.HomepageUrl,
		&i.License,
		&i.LatestVersion,
		&i.LatestVersionDate,
		&i.Deprecated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getScoreHistory = `-- name: GetScoreHistory :many
SELECT id, library_id, scored_at, overall_score, maintenance_health, api_clarity, doc_quality, security_posture, community_signal, deprecation_safety, scoring_version, raw_data FROM scores
WHERE library_id = $1
ORDER BY scored_at DESC
LIMIT $2
`

type GetScoreHistoryParams struct {
	LibraryID pgtype.UUID `json:"library_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetScoreHistory(ctx context.Context, arg GetScoreHistoryParams) ([]Score, error) {
	rows, err := q.db.Query(ctx, getScoreHistory, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Score{}
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ScoredAt,
			&i.OverallScore,
			&i.MaintenanceHealth,
			&i.ApiClarity,
			&i.DocQuality,
			&i.SecurityPosture,
			&i.CommunitySignal,
			&i.DeprecationSafety,
			&i.ScoringVersion,
			&i.RawData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkLibraryCategory = `-- name: LinkLibraryCategory :exec
INSERT INTO library_categories (library_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkLibraryCategoryParams struct {
	LibraryID  pgtype.UUID `json:"library_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) LinkLibraryCategory(ctx context.Context, arg LinkLibraryCategoryParams) error {
	_, err := q.db.Exec(ctx, linkLibraryCategory, arg.LibraryID, arg.CategoryID)
	return err
}

const listAllLibraries = `-- name: ListAllLibraries :many
SELECT id, name, registry, package_name, github_repo, description, homepage_url, license, latest_version, latest_version_date, deprecated, created_at, updated_at, metadata FROM libraries ORDER BY name
`

func (q *Queries) ListAllLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.Query(ctx, listAllLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Registry,
			&i.PackageName,
			&i.GithubRepo,
			&i.Description,
			&i.HomepageUrl,
			&i.License,
			&i.LatestVersion,
			&i.LatestVersionDate,
			&i.Deprecated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.slug, c.name, c.description, c.parent_id, COUNT(lc.library_id) AS library_count
FROM categories c
LEFT JOIN library_categories lc ON lc.category_id = c.id
GROUP BY c.id
ORDER BY c.name
`

type ListCategoriesRow struct {
	ID           pgtype.UUID `json:"id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	ParentID     pgtype.UUID `json:"parent_id"`
	LibraryCount int64       `json:"library_count"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.LibraryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT l.id, l.name, l.registry, l.package_name, l.github_repo, l.description, l.homepage_url, l.license, l.latest_version, l.latest_version_date, l.deprecated, l.created_at, l.updated_at, l.metadata, s.overall_score, COALESCE(s.scoring_version, '') AS scoring_version
FROM libraries l
LEFT JOIN LATERAL (
    SELECT overall_score, scoring_version
    FROM scores
    WHERE library_id = l.id
    ORDER BY scored_at DESC
    LIMIT 1
) s ON true
WHERE ($1::text = '' OR l.registry = $1)
  AND ($2::boolean IS NULL OR l.deprecated = $2)
ORDER BY COALESCE(s.overall_score, 0) DESC
LIMIT $3 OFFSET $4
`

type ListLibrariesParams struct {
	Column1 string `json:"column_1"`
	Column2 bool   `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListLibrariesRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Registry          string             `json:"registry"`
	PackageName       string             `json:"package_name"`
	GithubRepo        string             `json:"github_repo"`
	Description       string             `json:"description"`
	HomepageUrl       pgtype.Text        `json:"homepage_url"`
	License           string             `json:"license"`
	LatestVersion     string             `json:"latest_version"`
	LatestVersionDate pgtype.Timestamptz `json:"latest_version_date"`
	Deprecated        bool               `json:"deprecated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Metadata          []byte             `json:"metadata"`
	OverallScore      pgtype.Numeric     `json:"overall_score"`
	ScoringVersion    string             `json:"scoring_version"`
}

func (q *Queries) ListLibraries(ctx context.Context, arg ListLibrariesParams) ([]ListLibrariesRow, error) {
	rows, err := q.db.Query(ctx, listLibraries,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesRow{}
	for rows.Next() {
		var i ListLibrariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Registry,
			&i.PackageName,
			&i.GithubRepo,
			&i.Description,
			&i.HomepageUrl,
			&i.License,
			&i.LatestVersion,
			&i.LatestVersionDate,
			&i.Deprecated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
			&i.OverallScore,
			&i.ScoringVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesByCategory = `-- name: ListLibrariesByCategory :many
SELECT l.id, l.name, l.registry, l.package_name, l.github_repo, l.description, l.homepage_url, l.license, l.latest_version, l.latest_version_date, l.deprecated, l.created_at, l.updated_at, l.metadata, s.overall_score, COALESCE(s.scoring_version, '') AS scoring_version
FROM libraries l
JOIN library_categories lc ON lc.library_id = l.id
JOIN categories c ON c.id = lc.category_id
LEFT JOIN LATERAL (
    SELECT overall_score, scoring_version
    FROM scores
    WHERE library_id = l.id
    ORDER BY scored_at DESC
    LIMIT 1
) s ON true
WHERE c.slug = $1
ORDER BY COALESCE(s.overall_score, 0) DESC
LIMIT $2 OFFSET $3
`

type ListLibrariesByCategoryParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListLibrariesByCategoryRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Registry          string             `json:"registry"`
	PackageName       string             `json:"package_name"`
	GithubRepo        string             `json:"github_repo"`
	Description       string             `json:"description"`
	HomepageUrl       pgtype.Text        `json:"homepage_url"`
	License           string             `json:"license"`
	LatestVersion     string             `json:"latest_version"`
	LatestVersionDate pgtype.Timestamptz `json:"latest_version_date"`
	Deprecated        bool               `json:"deprecated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Metadata          []byte             `json:"metadata"`
	OverallScore      pgtype.Numeric     `json:"overall_score"`
	ScoringVersion    string             `json:"scoring_version"`
}

func (q *Queries) ListLibrariesByCategory(ctx context.Context, arg ListLibrariesByCategoryParams) ([]ListLibrariesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listLibrariesByCategory, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesByCategoryRow{}
	for rows.Next() {
		var i ListLibrariesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Registry,
			&i.PackageName,
			&i.GithubRepo,
			&i.Description,
			&i.HomepageUrl,
			&i.License,
			&i.LatestVersion,
			&i.LatestVersionDate,
			&i.Deprecated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
			&i.OverallScore,
			&i.ScoringVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLibraries = `-- name: SearchLibraries :many
SELECT id, name, registry, package_name, github_repo, description, homepage_url, license, latest_version, latest_version_date, deprecated, created_at, updated_at, metadata FROM libraries
WHERE name ILIKE '%' || $1 || '%'
   OR description ILIKE '%' || $1 || '%'
   OR package_name ILIKE '%' || $1 || '%'
LIMIT $2 OFFSET $3
`

type SearchLibrariesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchLibraries(ctx context.Context, arg SearchLibrariesParams) ([]Library, error) {
	rows, err := q.db.Query(ctx, searchLibraries, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Registry,
			&i.PackageName,
			&i.GithubRepo,
			&i.Description,
			&i.HomepageUrl,
			&i.License,
			&i.LatestVersion,
			&i.LatestVersionDate,
			&i.Deprecated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionRun = `-- name: UpdateCollectionRun :exec
UPDATE collection_runs SET
    completed_at = now(),
    status = $2,
    libraries_processed = $3,
    libraries_succeeded = $4,
    libraries_failed = $5,
    success_rate = $6,
    errors = $7
WHERE id = $1
`

type UpdateCollectionRunParams struct {
	ID                 pgtype.UUID    `json:"id"`
	Status             string         `json:"status"`
	LibrariesProcessed int32          `json:"libraries_processed"`
	LibrariesSucceeded int32          `json:"libraries_succeeded"`
	LibrariesFailed    int32          `json:"libraries_failed"`
	SuccessRate        pgtype.Numeric `json:"success_rate"`
	Errors             []byte         `json:"errors"`
}

func (q *Queries) UpdateCollectionRun(ctx context.Context, arg UpdateCollectionRunParams) error {
	_, err := q.db.Exec(ctx, updateCollectionRun,
		arg.ID,
		arg.Status,
		arg.LibrariesProcessed,
		arg.LibrariesSucceeded,
		arg.LibrariesFailed,
		arg.SuccessRate,
		arg.Errors,
	)
	return err
}

const updateCollectionRunItem = `-- name: UpdateCollectionRunItem :exec
UPDATE collection_run_items SET
    status = $2,
    error_message = $3,
    duration_ms = $4,
    completed_at = now()
WHERE id = $1
`

type UpdateCollectionRunItemParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	DurationMs   int32       `json:"duration_ms"`
}

func (q *Queries) UpdateCollectionRunItem(ctx context.Context, arg UpdateCollectionRunItemParams) error {
	_, err := q.db.Exec(ctx, updateCollectionRunItem,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	return err
}

const updateLibrary = `-- name: UpdateLibrary :exec
UPDATE libraries SET
    name = $2,
    description = $3,
    homepage_url = $4,
    license = $5,
    latest_version = $6,
    latest_version_date = $7,
    deprecated = $8,
    metadata = $9,
    updated_at = now()
WHERE id = $1
`

type UpdateLibraryParams struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	HomepageUrl       pgtype.Text        `json:"homepage_url"`
	License           string             `json:"license"`
	LatestVersion     string             `json:"latest_version"`
	LatestVersionDate pgtype.Timestamptz `json:"latest_version_date"`
	Deprecated        bool               `json:"deprecated"`
	Metadata          []byte             `json:"metadata"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) error {
	_, err := q.db.Exec(ctx, updateLibrary,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.HomepageUrl,
		arg.License,
		arg.LatestVersion,
		arg.LatestVersionDate,
		arg.Deprecated,
		arg.Metadata,
	)
	return err
}
